swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /readings:
    get:
      operationId: "readings.read"
      tags:
        - "Readings"
      summary: "The readings data structure supported by the server application"
      description: "Get the list of readings"
      responses:
        200:
          description: "Successful read readings list operation"
          schema:
            type: "array"
            items:
              properties:
                baro_temp:
                  type: "number"
                baro_pressure:
                  type: "number"
                cpu_temp:
                  type: "number"
                humid_temp:
                  type: "number"
                humid_humid:
                  type: "number"
                light:
                  type: "integer"
                time:
                  type: "number"
